### PR TITLE
Clean up: workflow recipe version

### PR DESCRIPTION
**Pull request by UlrikeS91**
MINOR changes:
- improved instructions
- establish alphabetical order
- fixed indentation

MAJOR changes:
none

SPECIAL ATTENTION:
- renamed `format` to `usedFormat`: because format has been used to express the format of the type of schema, e.g. file has a format with instructions to add the content type OF the file, here the instructions ask for USED content types

### CODE REVIEW

**Comment by lzehl** [comment]
@apdavison could you clarify what format /usedFormat is exactly referring to? the content type of all the components?

**Review by lzehl — COMMENTED** [review]
looks okay. I need clarification from @apdavison for the format

**Review by apdavison — COMMENTED** [review]
It should be `format`, not `usedFormat`.

This refers to the content type of the workflow recipe file, for example `application/vnd.commonworkflowlanguage.commandlinetool` or `application/vnd.commonworkflowlanguage.workflow` (which reminds me, these two have not yet been added to the instances)

**Comment by UlrikeS91** [comment]
> It should be `format`, not `usedFormat`.
> 
> This refers to the content type of the workflow recipe file, for example `application/vnd.commonworkflowlanguage.commandlinetool` or `application/vnd.commonworkflowlanguage.workflow` (which reminds me, these two have not yet been added to the instances)

That's fine. Then what you meant was the format of the recipe and not formats used by it. I will fix the instructions and change the property name back to `format.`

**Review by lzehl — APPROVED** [review]

**Comment by lzehl** [comment]
@apdavison feel free to merge if you also approve

**Pull request merged**
