### PR TITLE
Add schemas for web services

### PR DESCRIPTION
**Pull request by apdavison**

### CODE REVIEW

**Review by lzehl — COMMENTED** [review]
@apdavison I have some questions: 
+ Do web services potentially have all properties from a research product (version)?
+ Do input and output formats not equal all input and output formats from the attached software versions? If yes should we leave this up to the software version to facilitate maintenance?
+ Are there really no other web service specific properties needed here?
 
@bweyers it would be good to hear you opinion here as well, I think.

**Comment by apdavison** [comment]
> * Do web services potentially have all properties from a research product (version)?

Yes. The web services we're concerned with are essentially Software-as-a-Service, so they have the same properties as Software.

> * Do input and output formats not equal all input and output formats from the attached software versions? If yes should we leave this up to the software version to facilitate maintenance?

No. A web service might be made up from several pieces of software, only some of which are relevant to the input/output formats of the service.

> * Are there really no other web service specific properties needed here?

I can't think of any.

**Comment by lzehl** [comment]
@apdavison from my side we can merge this one then

**Comment by apdavison** [comment]
This topic came up in the HLST meeting. I'm wondering if the WebService and WebServiceVersion schemas should in fact be in "core", alongside Software and SoftwareVersion.

If you agree, @lzehl, I'll make a PR.

**Comment by lzehl** [comment]
@apdavison I agree. With https://github.com/HumanBrainProject/openMINDS_core/issues/368 this would indeed make sense and solve two issues at the same time

**Comment by apdavison** [comment]
replaced by https://github.com/HumanBrainProject/openMINDS_core/pull/369

**Pull request closed without merging**
