### PR TITLE
updating openMINDS_computation for upcoming openMINDS v3 release

### PR DESCRIPTION
**Pull request by lzehl**
**Update computation.schema.tpl.json**
input & output are already required properties of Activity schema; required list is extended not overwritten, therefore only additional required properties need to be mentioned in the extending schemas

### CODE REVIEW

**Comment by lzehl** [comment]
@apdavison I went through the schemas, made some corrections, but have now some questions to see if further modifications are needed for a nice integration with the other openMINDS submodules.

**1) Should we move the HardwareSystem schema to openMINDS_core?** I think this will be used by more extensions and could even be integrated within core itself (at least as option in keywords, or on ProtocolExecution as optional field)

**2) I did not understand fully the need of a SoftwareAgent. Could you comment?** As far as I saw the SoftwareAgent has a name, is linked to Computation, and links to a SoftwareVersion and an Environment, but the Environment itself links to to a SoftwareVersion and is linked to Computation. Besides an additional name I do not see any information in addition to Environment. I would change this to either **(A)** delete SoftwareAgent, make "hardware" optional in Environment (if a software can run without a hardware) and maybe rename Environment to Agent?; **(B)** delete SoftwareAgent, delete property "environment" from Computation, change _linkedTypes of "startedBy" in Computation to SoftwareVersion OR Environment (if a software can run without a hardware); OR **(C)** delete property "environment" from Computation (to only keep Environment via SoftwareAgent

**3) (connected to/dependent on 2) There are too many options to add ParameterSets.** Meaning **(i)** Computation has a ParameterSet (inherited from Activity) (ii) LaunchConfiguration has a ParameterSet for "environmentVariables", and (iii) Environment has a ParameterSet for "configuration". I suggest **(A)** we remove ParameterSet from Activity in core and make it part of the ProtocolExecution only; AND either **(B)** delete "environmentVariables" from LaunchConfiguration OR **(C)** delete "launchConfiguration" from Computation and change in Environment "configuration" to _linkedTypes LaunchConfiguration. 

**4) Why does the WorkflowExecution "stages" only Simulation, Visualization and  DataAnalysis, and not also Computation and Optimization?** Connected to that question why do Simulation, DataAnalysis and Optimization have to be separate schemas? DataAnalysis and Visualization are essentially the same as Computation, Optimization differs slightly in input/output and Simulation only in the input. Could we not be a bit more generic and just allow all needed input/outputs for the Computation and remove the other schemas (leaving the combination to common sense)? If yes, I would just introduce a "computationType" property to link to new controlledTerms/ComputationType (instances: simulation, data analysis, optimization, etc).

**Comment by lzehl** [comment]
@apdavison depending on your feedback to my questions I can integrate further changes within this PR. I guess this extension is not yet actively used by you so that non-backwards compatible changes on this dev branch should be okay, correct?

**Comment by apdavison** [comment]
> **1) Should we move the HardwareSystem schema to openMINDS_core?** I think this will be used by more extensions and could even be integrated within core itself (at least as option in keywords, or on ProtocolExecution as optional field)

Here HardwareSystem is specifically computer hardware, and so I think it belongs in "computation" since it is unlikely another extension would need to specify computing hardware without also specifying the software.

It might be useful to have a representation of hardware in general in core, and then "computation" could inherit from that. I think we already discussed having Device from "ephys" in core?

> **2) I did not understand fully the need of a SoftwareAgent. Could you comment?** As far as I saw the SoftwareAgent has a name, is linked to Computation, and links to a SoftwareVersion and an Environment, but the Environment itself links to to a SoftwareVersion and is linked to Computation. Besides an additional name I do not see any information in addition to Environment. I would change this to either **(A)** delete SoftwareAgent, make "hardware" optional in Environment (if a software can run without a hardware) and maybe rename Environment to Agent?; **(B)** delete SoftwareAgent, delete property "environment" from Computation, change _linkedTypes of "startedBy" in Computation to SoftwareVersion OR Environment (if a software can run without a hardware); OR **(C)** delete property "environment" from Computation (to only keep Environment via SoftwareAgent

SoftwareAgent can be used in the same place as Person, when we want to know _who_ launched a given computation. Sometimes it is not a human person who runs a computation, it could be a cron job or a continuous integration system.

The Environment/Software that the SoftwareAgent will be linked to are not the same as those that the Computation it launches are linked to.

> **3) (connected to/dependent on 2) There are too many options to add ParameterSets.** Meaning **(i)** Computation has a ParameterSet (inherited from Activity) (ii) LaunchConfiguration has a ParameterSet for "environmentVariables", and (iii) Environment has a ParameterSet for "configuration". I suggest **(A)** we remove ParameterSet from Activity in core and make it part of the ProtocolExecution only; AND either **(B)** delete "environmentVariables" from LaunchConfiguration OR **(C)** delete "launchConfiguration" from Computation and change in Environment "configuration" to _linkedTypes LaunchConfiguration.

I'm afraid **all** of these ParameterSets  are needed to represent a computation. For reproducibility we need to distinguish (i) the persistent configuration of an environment, (ii) the specific environment variables passed when launching a specific computation, (iii) a parameter file that acts as an input to the computation.

Item (iii) could be represented as a File, but this makes it more opaque and reduces the possibilities of performing queries based on parameterisations, so I'd like the option to represent such inputs as ParameterSets.

> **4) Why does the WorkflowExecution "stages" only Simulation, Visualization and DataAnalysis, and not also Computation and Optimization?** Connected to that question why do Simulation, DataAnalysis and Optimization have to be separate schemas? DataAnalysis and Visualization are essentially the same as Computation, Optimization differs slightly in input/output and Simulation only in the input. Could we not be a bit more generic and just allow all needed input/outputs for the Computation and remove the other schemas (leaving the combination to common sense)? If yes, I would just introduce a "computationType" property to link to new controlledTerms/ComputationType (instances: simulation, data analysis, optimization, etc).

"stages" should include Optimization, that's an oversight on my part. Computation is an abstract schema, it should always be inherited and should never have any instances.

We could be more generic, I don't feel strongly about it. There are three reasons for using subclasses:
1. efficiency. We are likely to end up with hundreds of thousands or even millions of Simulation and DataAnalysis instances in the KG, and separating them will make queries a bit faster.
2. quality control. One of the reasons for using JSON Schema, as of course you know, is that it allows checks on the types of linked objects.
3. automated UI. I understood that the choice of JSON Schema over SHACL was that it was easier to use it for automated UI generation, in which only objects of the appropriate type show up.

**Comment by lzehl** [comment]
@apdavison thanks for your explanations :)

**For 1)** I understand. I will have a look at this over the weekend and provide the schema on core the HardwareSystem schema can inherit from.

**For 2 & 3)** I understand now, thanks for the clarification.

**For 4)** Ah okay. I've removed then the "_type" from the Computation schema to identify this as a concept schema and added Optimization to the "stages" in WorkflowExecution.

Then this PR should be ready, I think. The extension part from core I can add next week in another PR

**Comment by lzehl** [comment]
@apdavison would you merge this PR or is there an issue left that you need solving first? 
I've opened an issue for device/hardware in core. Adoptions as result of this issue can be done in a separate PR. okay?

**Pull request merged**
